#Requires AutoHotkey v2.0
#SingleInstance Force

; ============================================================
; Plex Pre-roll Holiday Switcher (AHK v2)
; GUI only — all Plex logic lives in a PowerShell script that
; Task Scheduler runs daily. No AHK needed after compile.
;
; AppData folder: %AppData%\PlexPrerollSwitcher\
;   settings.ini     — saved GUI settings
;   PlexSwitch.ps1   — generated PS script (Task Scheduler runs this)
;   run.log          — log of all runs
;   last_run.ini     — status of last scheduled run (shown in GUI)
; ============================================================

AppDir     := A_AppData "\PlexPrerollSwitcher"
DirCreate(AppDir)
CfgFile    := AppDir "\settings.ini"
LogFile    := AppDir "\run.log"
StatusFile := AppDir "\last_run.ini"
PSFile     := AppDir "\PlexSwitch.ps1"

; --------------------------------------------------
; INI helpers
; --------------------------------------------------
IniReadSafe(section, key, default := "") {
    global CfgFile
    try {
        return IniRead(CfgFile, section, key, default)
    } catch {
        return default
    }
}

IniWriteSafe(value, section, key) {
    global CfgFile
    try {
        IniWrite(value, CfgFile, section, key)
    } catch {
        ; ignore
    }
}

AppendLog(line) {
    global LogFile
    try {
        FileAppend(line . "`r`n", LogFile, "UTF-8")
    } catch {
        ; ignore
    }
}

; --------------------------------------------------
; Build the PowerShell script that Task Scheduler runs.
; It contains all holiday logic, date checking, and
; the Plex API call — no AHK needed at runtime.
; --------------------------------------------------
BuildPowerShellScript(url, token, paths1, paths2) {
    n := "`n"
    q := "`""

    ; Helper to safely single-quote a value for PS
    PSQ(val) {
        return "'" . StrReplace(val, "'", "''") . "'"
    }

    ps := ""
    ps .= "# Plex Pre-roll Holiday Switcher — Auto-generated by HolidaySwitcher" . n
    ps .= "# Runs daily via Task Scheduler. Edit settings in the GUI, not here." . n
    ps .= n

    ; --- Settings baked in ---
    ps .= "$PlexUrl   = " . PSQ(url)   . n
    ps .= "$Token     = " . PSQ(token) . n
    ps .= "$LogFile   = " . PSQ(AppDir . "\run.log")      . n
    ps .= "$StatusFile = " . PSQ(AppDir . "\last_run.ini") . n
    ps .= n

    ; --- Preroll paths baked in ---
    ps .= "# Preroll paths — File1,File2 joined with comma for Plex" . n
    ps .= "$Prerolls = @{}" . n
    for key in ["Default","Halloween","Thanksgiving","Christmas","Valentines","AprilFools","July4th","MardiGras","Easter"] {
        p1 := Trim(paths1[key])
        p2 := Trim(paths2[key])
        combined := (p1 != "" && p2 != "") ? p1 . "," . p2 : p1
        ps .= '$Prerolls[' . PSQ(key) . '] = ' . PSQ(combined) . n
    }
    ps .= n

    ; --- Logging helper ---
    ps .= "function Write-Log([string]$msg) {" . n
    ps .= "  $ts = (Get-Date).ToString('yyyy-MM-ddTHH:mm:ss')" . n
    ps .= "  $line = " . q . "[$ts] $msg" . q . n
    ps .= "  Add-Content -Path $LogFile -Value $line" . n
    ps .= "}" . n
    ps .= n

    ; --- Status file writer ---
    ps .= "function Write-Status([string]$holiday, [string]$result) {" . n
    ps .= "  $date = (Get-Date).ToString('MMM d yyyy h:mm tt')" . n
    ps .= "  Set-Content -Path $StatusFile -Value " . q . "[LastRun]`nDate=$date`nHoliday=$holiday`nResult=$result" . q . n
    ps .= "}" . n
    ps .= n

    ; --- Toast notification ---
    ps .= "function Show-Toast([string]$title, [string]$msg) {" . n
    ps .= "  try {" . n
    ps .= "    [Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType=WindowsRuntime] | Out-Null" . n
    ps .= "    $xml = [Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent(0)" . n
    ps .= "    $xml.GetElementsByTagName('text')[0].InnerText = $title" . n
    ps .= "    $xml.GetElementsByTagName('text')[1].InnerText = $msg" . n
    ps .= "    $toast = [Windows.UI.Notifications.ToastNotification]::new($xml)" . n
    ps .= "    [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier('Plex Preroll Switcher').Show($toast)" . n
    ps .= "  } catch {}" . n
    ps .= "}" . n
    ps .= n

    ; --- Easter algorithm ---
    ps .= "function Get-EasterDate([int]$year) {" . n
    ps .= "  $a = $year % 19" . n
    ps .= "  $b = [Math]::Floor($year / 100)" . n
    ps .= "  $c = $year % 100" . n
    ps .= "  $d = [Math]::Floor($b / 4)" . n
    ps .= "  $e = $b % 4" . n
    ps .= "  $f = [Math]::Floor(($b + 8) / 25)" . n
    ps .= "  $g = [Math]::Floor(($b - $f + 1) / 3)" . n
    ps .= "  $h = (19*$a + $b - $d - $g + 15) % 30" . n
    ps .= "  $i = [Math]::Floor($c / 4)" . n
    ps .= "  $k = $c % 4" . n
    ps .= "  $l = (32 + 2*$e + 2*$i - $h - $k) % 7" . n
    ps .= "  $m = [Math]::Floor(($a + 11*$h + 22*$l) / 451)" . n
    ps .= "  $month = [Math]::Floor(($h + $l - 7*$m + 114) / 31)" . n
    ps .= "  $day   = (($h + $l - 7*$m + 114) % 31) + 1" . n
    ps .= "  return Get-Date -Year $year -Month $month -Day $day" . n
    ps .= "}" . n
    ps .= n

    ; --- Thanksgiving: 4th Thursday of November ---
    ps .= "function Get-ThanksgivingDate([int]$year) {" . n
    ps .= "  $d = Get-Date -Year $year -Month 11 -Day 1" . n
    ps .= "  while ($d.DayOfWeek -ne 'Thursday') { $d = $d.AddDays(1) }" . n
    ps .= "  return $d.AddDays(21)" . n
    ps .= "}" . n
    ps .= n

    ; --- Holiday window check ---
    ; Returns holiday key if today is within the window, else empty string
    ps .= "function Get-HolidayKey {" . n
    ps .= "  $today = (Get-Date).Date" . n
    ps .= "  $y = $today.Year" . n
    ps .= n
    ps .= "  function In-Window($date, $before, $after) {" . n
    ps .= "    $diff = ($today - $date.Date).TotalDays" . n
    ps .= "    return ($diff -ge -$before -and $diff -le $after)" . n
    ps .= "  }" . n
    ps .= n
    ps .= "  if (In-Window (Get-Date -Year $y -Month 2  -Day 14) 7 0) { return 'Valentines' }" . n
    ps .= "  if (In-Window (Get-Date -Year $y -Month 4  -Day 1)  0 3) { return 'AprilFools' }" . n
    ps .= "  if (In-Window (Get-Date -Year $y -Month 7  -Day 4)  7 0) { return 'July4th' }" . n
    ps .= "  if (In-Window (Get-Date -Year $y -Month 10 -Day 31) 7 0) { return 'Halloween' }" . n
    ps .= "  if (In-Window (Get-ThanksgivingDate $y)              7 0) { return 'Thanksgiving' }" . n
    ps .= "  if (In-Window (Get-Date -Year $y -Month 12 -Day 25) 7 0) { return 'Christmas' }" . n
    ps .= "  $easter = Get-EasterDate $y" . n
    ps .= "  if (In-Window $easter                    7 0) { return 'Easter' }" . n
    ps .= "  if (In-Window $easter.AddDays(-47)       7 0) { return 'MardiGras' }" . n
    ps .= "  return ''" . n
    ps .= "}" . n
    ps .= n

    ; --- Main logic ---
    ps .= "Write-Log '---- Auto Apply ----'" . n
    ps .= n
    ps .= "$holidayKey = Get-HolidayKey" . n
    ps .= "$chosen = ''" . n
    ps .= "if ($holidayKey -ne '' -and $Prerolls[$holidayKey] -ne '') {" . n
    ps .= "  $chosen = $Prerolls[$holidayKey]" . n
    ps .= "}" . n
    ps .= "if ($chosen -eq '') {" . n
    ps .= "  $chosen = $Prerolls['Default']" . n
    ps .= "}" . n
    ps .= n
    ps .= "$label = if ($holidayKey -ne '') { $holidayKey } else { 'Default' }" . n
    ps .= "Write-Log " . q . "Holiday: $label" . q . n
    ps .= "Write-Log " . q . "Chosen:  $chosen" . q . n
    ps .= n
    ps .= "if ($chosen -eq '') {" . n
    ps .= "  Write-Log 'Nothing to apply — Default is blank.'" . n
    ps .= "  Write-Status $label 'Skipped'" . n
    ps .= "  Show-Toast 'Plex Preroll Switcher' 'Skipped — no preroll configured.'" . n
    ps .= "  exit 0" . n
    ps .= "}" . n
    ps .= n
    ps .= "try {" . n
    ps .= "  $encoded = [uri]::EscapeDataString($chosen)" . n
    ps .= "  $uri = " . q . "$PlexUrl/:/prefs?X-Plex-Token=$Token&CinemaTrailersPrerollID=$encoded" . q . n
    ps .= "  Write-Log " . q . "PUT $uri" . q . n
    ps .= "  Invoke-WebRequest -Uri $uri -Method Put -UseBasicParsing | Out-Null" . n
    ps .= "  Write-Log 'PUT completed.'" . n
    ps .= n
    ps .= "  $xml = (Invoke-WebRequest -Uri " . q . "$PlexUrl/:/prefs?X-Plex-Token=$Token" . q . " -UseBasicParsing).Content" . n
    ps .= "  $pat = '<Setting id=' + [char]34 + 'CinemaTrailersPrerollID' + [char]34 + '[^>]+>'" . n
    ps .= "  $m = [regex]::Match($xml, $pat)" . n
    ps .= "  $vPat = 'value=' + [char]34 + '([^' + [char]34 + ']*)' + [char]34" . n
    ps .= "  if ($m.Success -and $m.Value -match $vPat) {" . n
    ps .= "    if ($Matches[1] -eq $chosen) {" . n
    ps .= "      Write-Log 'SUCCESS: Plex preroll matches.'" . n
    ps .= "      Write-Status $label 'SUCCESS'" . n
    ps .= "      Show-Toast 'Plex Preroll Switcher' " . q . "SUCCESS — $label preroll active." . q . n
    ps .= "    } else {" . n
    ps .= "      Write-Log 'WARNING: Plex value did not match.'" . n
    ps .= "      Write-Status $label 'WARNING — mismatch'" . n
    ps .= "      Show-Toast 'Plex Preroll Switcher' 'WARNING — preroll sent but Plex value did not match.'" . n
    ps .= "    }" . n
    ps .= "  } else {" . n
    ps .= "    Write-Log 'SUCCESS (unverified — could not parse Plex response).'" . n
    ps .= "    Write-Status $label 'SUCCESS (unverified)'" . n
    ps .= "  }" . n
    ps .= "} catch {" . n
    ps .= "  Write-Log " . q . "ERROR: $($_.Exception.Message)" . q . n
    ps .= "  Write-Status $label 'FAILED'" . n
    ps .= "  Show-Toast 'Plex Preroll Switcher' 'FAILED — could not update Plex. Check log.'" . n
    ps .= "  exit 1" . n
    ps .= "}" . n

    return ps
}

; --------------------------------------------------
; Write PS file and register Task Scheduler task
; --------------------------------------------------
DeployScript(url, token, paths1, paths2) {
    global PSFile, AppDir, LogFile

    ; Write the PowerShell script
    ps := BuildPowerShellScript(url, token, paths1, paths2)
    try FileDelete(PSFile)
    FileAppend(ps, PSFile, "UTF-8")
    AppendLog("Wrote PlexSwitch.ps1")

    ; Build elevated PS to register the task
    n := "`n"
    reg := ""
    reg .= "$psFile   = '" . StrReplace(PSFile,   "'", "''") . "'" . n
    reg .= "$logFile  = '" . StrReplace(LogFile,  "'", "''") . "'" . n
    reg .= "$action   = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument " . '"-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ""$psFile"""' . n
    reg .= "$trigger  = New-ScheduledTaskTrigger -Daily -At '06:00'" . n
    reg .= "$settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -ExecutionTimeLimit (New-TimeSpan -Minutes 5)" . n
    reg .= "# Remove old tasks from previous versions" . n
    reg .= "@('PlexPreroll_Default','PlexPreroll_Halloween','PlexPreroll_Christmas'," . n
    reg .= " 'PlexPreroll_Valentines','PlexPreroll_AprilFools','PlexPreroll_July4th'," . n
    reg .= " 'PlexPreroll_Thanksgiving','PlexPreroll_Easter','PlexPreroll_MardiGras'," . n
    reg .= " 'PlexPreroll_Switcher') | ForEach-Object {" . n
    reg .= "  Unregister-ScheduledTask -TaskName $_ -Confirm:$false -ErrorAction SilentlyContinue" . n
    reg .= "}" . n
    reg .= "Register-ScheduledTask -TaskName 'PlexPreroll_Switcher' -Action $action -Trigger $trigger -Settings $settings -RunLevel Highest -Force | Out-Null" . n
    reg .= "Add-Content -Path $logFile -Value '[Task] Registered PlexPreroll_Switcher -> powershell PlexSwitch.ps1'" . n

    regFile := AppDir "\RegisterTask.ps1"
    try FileDelete(regFile)
    FileAppend(reg, regFile, "UTF-8")

    ; Run elevated
    elevateCmd := 'powershell.exe -NoProfile -WindowStyle Hidden -Command '
        . '"Start-Process powershell -Verb RunAs -Wait -ArgumentList '
        . "'" . '-NoProfile -ExecutionPolicy Bypass -File "' . regFile . '" *>> "' . LogFile . '"' . "'"
        . '"'

    RunWait(elevateCmd, , "Hide")
    AppendLog("Task registration complete.")
}

; --------------------------------------------------
; Load saved settings
; --------------------------------------------------
holidays := ["Default","Halloween","Thanksgiving","Christmas","Valentines","AprilFools","July4th","MardiGras","Easter"]

savedUrl   := IniReadSafe("Plex", "Url",   "http://localhost:32400")
savedToken := IniReadSafe("Plex", "Token", "")
saved1 := Map()
saved2 := Map()
for h in holidays {
    saved1[h] := IniReadSafe("Files", h . "_1", "")
    saved2[h] := IniReadSafe("Files", h . "_2", "")
}

; --------------------------------------------------
; GUI
; --------------------------------------------------
g := Gui("+Resize", "Plex Pre-roll Holiday Switcher")
g.SetFont("s10", "Segoe UI")

labelW := 120
editW  := 270
btnW   := 70
gapX   := 8
totalW := labelW + (editW + btnW + gapX) * 2

rowY := 12

g.AddText("x12 y" rowY " w" totalW, "Plex Server URL (ex: http://localhost:32400)")
rowY += 18
edUrl := g.AddEdit("x12 y" rowY " w" totalW " h20", savedUrl)
rowY += 28

g.AddText("x12 y" rowY " w" labelW, "Plex Token")
rowY += 18
edToken := g.AddEdit("x12 y" rowY " w" totalW " h20 Password", savedToken)
rowY += 24

g.AddLink("x12 y" rowY, '<a href="https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/">How to find your Plex Token</a>')
rowY += 26

g.AddText("x12 y" rowY " w" totalW,
    "UNC paths supported e.g. \\192.168.1.0\share\file.mp4  |  File 2 plays after File 1.")
rowY += 20

xE1 := 12 + labelW + gapX
xB1 := xE1 + editW + 4
xE2 := xB1 + btnW + gapX
xB2 := xE2 + editW + 4

g.AddText("x" xE1 " y" rowY " w" editW, "Preroll File 1  (required)")
g.AddText("x" xE2 " y" rowY " w" editW, "Preroll File 2  (optional)")
rowY += 18

edits1 := Map()
edits2 := Map()

AddHolidayRow(gui, y, label, key) {
    global labelW, editW, btnW, gapX, xE1, xB1, xE2, xB2
    global edits1, edits2, saved1, saved2
    gui.AddText("x12 y" (y+3) " w" labelW, label)
    e1 := gui.AddEdit("x" xE1 " y" y " w" editW " h20", saved1[key])
    b1 := gui.AddButton("x" xB1 " y" (y-1) " w" btnW " h22", "Browse")
    b1.OnEvent("Click", (*) => BrowseIntoEdit(e1))
    e2 := gui.AddEdit("x" xE2 " y" y " w" editW " h20", saved2[key])
    b2 := gui.AddButton("x" xB2 " y" (y-1) " w" btnW " h22", "Browse")
    b2.OnEvent("Click", (*) => BrowseIntoEdit(e2))
    edits1[key] := e1
    edits2[key] := e2
    return y + 28
}

BrowseIntoEdit(ed) {
    file := FileSelect(3, "", "Select preroll video", "Video Files (*.mp4;*.m4v;*.mov;*.mkv;*.webm)")
    if (file != "")
        ed.Value := file
}

labels := Map(
    "Default",      "Default",
    "Halloween",    "Halloween",
    "Thanksgiving", "Thanksgiving",
    "Christmas",    "Christmas",
    "Valentines",   "Valentine's Day",
    "AprilFools",   "April Fools",
    "July4th",      "July 4th",
    "MardiGras",    "Mardi Gras",
    "Easter",       "Easter"
)

for h in holidays
    rowY := AddHolidayRow(g, rowY, labels[h], h)

rowY += 10
btnSave := g.AddButton("x12 y" rowY " w160 h32 Default", "Save && Apply")
status  := g.AddLink("x184 y" (rowY+9) " w" (totalW-172), "Status: Ready.")
rowY += 42

; Last auto-run status
lastRun := "Last auto-run: Never"
try {
    lastDate    := IniRead(StatusFile, "LastRun", "Date",    "Never")
    lastResult  := IniRead(StatusFile, "LastRun", "Result",  "Unknown")
    lastHoliday := IniRead(StatusFile, "LastRun", "Holiday", "")
    lastLabel   := (lastHoliday = "" || lastHoliday = "none") ? "Default" : lastHoliday
    lastRun     := "Last auto-run: " . lastDate . " — " . lastLabel . " — " . lastResult
} catch {
    ; file not written yet
}
g.AddText("x12 y" rowY " w" totalW, lastRun)
rowY += 22

g.AddText("x12 y" rowY " w" totalW, "Version 3. Created by Stacy Edenton.")
rowY += 18
g.AddLink("x12 y" rowY, '<a href="https://stacyedenton.com">https://stacyedenton.com</a>')

btnSave.OnEvent("Click", (*) => SaveAndApply())
g.Show("w" (totalW+24) " h" (rowY+40))

; --------------------------------------------------
; Save & Apply
; --------------------------------------------------
SaveAndApply() {
    global edUrl, edToken, edits1, edits2, holidays, status, LogFile, AppDir, PSFile

    url   := Trim(edUrl.Value)
    token := Trim(edToken.Value)

    if (url = "") {
        status.Text := "Status: Plex URL is required."
        return
    }
    if (token = "") {
        status.Text := "Status: Plex Token is required."
        return
    }

    ; Collect paths
    paths1 := Map()
    paths2 := Map()
    for h in holidays {
        paths1[h] := Trim(edits1[h].Value)
        paths2[h] := Trim(edits2[h].Value)
    }

    ; Save to INI
    IniWriteSafe(url,   "Plex", "Url")
    IniWriteSafe(token, "Plex", "Token")
    for h in holidays {
        IniWriteSafe(paths1[h], "Files", h . "_1")
        IniWriteSafe(paths2[h], "Files", h . "_2")
    }

    ; Write PS script + register task (UAC prompt)
    status.Text := "Status: Writing script and registering task (UAC prompt may appear)..."
    DeployScript(url, token, paths1, paths2)

    ; Apply right now by running the PS script immediately
    status.Text := "Status: Applying to Plex now..."
    cmd := 'powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "' . PSFile . '" >> "' . LogFile . '" 2>>&1'
    RunWait(A_ComSpec . ' /c ' . cmd, , "Hide")

    ; Read result from status file
    try {
        result  := IniRead(StatusFile, "LastRun", "Result",  "Unknown")
        holiday := IniRead(StatusFile, "LastRun", "Holiday", "")
        label   := (holiday = "" || holiday = "none") ? "Default" : holiday
        if InStr(result, "SUCCESS")
            status.Text := "Status: SUCCESS — " . label . " preroll set. Task scheduled daily at 6 AM."
        else if InStr(result, "WARNING")
            status.Text := "Status: WARNING — sent but Plex value didn't match. <a href=`"" . LogFile . "`">Open log</a>"
        else if InStr(result, "Skipped")
            status.Text := "Status: Saved. Skipped apply — Default is blank."
        else
            status.Text := "Status: FAILED. <a href=`"" . LogFile . "`">Open log</a>"
    } catch {
        status.Text := "Status: Done — check log for details. <a href=`"" . LogFile . "`">Open log</a>"
    }
}
